const form = document.querySelector('form')
let name = document.getElementById('name')
let email = document.getElementById('email')
let subject = document.getElementById('subject')
let message = document.getElementById('message')
let submit = document.querySelector('submit')
let sent = document.querySelector('.sent')
